!/bin/bash

# Create the bridged controller

  set -e
  set -x



  apt -y purge wolfram-engine

  # Get any updates / install and remove pacakges
  apt update -y
  if [ $UPGRADE = "1" ];then
   /bin/bash -c 'APT_LISTCHANGES_FRONTEND=none apt -y dist-upgrade'
  fi

  if [ $RELEASE = "BUSTER" -o $RELEASE = "RASPIOS32BUSTER" -o $RELEASE = "RASPIOS64BUSTER" ];then
   INSTALLEXTRA+=" initramfs-tools-core wiringpi python-smbus  python-usb python-libusb1"
  elif [ $RELEASE = "RASPIOS32BULLSEYE" -o $RELEASE = "RASPIOS64BULLSEYE" ];then
   INSTALLEXTRA+=" initramfs-tools-core python3-smbus python3-usb python3-libusb1"
  fi

  apt -y install rpiboot bridge-utils screen minicom subversion git libusb-1.0-0-dev nfs-kernel-server busybox python3-smbus $INSTALLEXTRA

  # Setup ready for iptables for NAT for NAT/WiFi use
  # Preseed answers for iptables-persistent install
  /bin/bash -c "echo 'iptables-persistent iptables-persistent/autosave_v4 boolean false' | debconf-set-selections"
  /bin/bash -c "echo 'iptables-persistent iptables-persistent/autosave_v6 boolean false' | debconf-set-selections"

  /bin/bash -c 'APT_LISTCHANGES_FRONTEND=none apt -y install iptables-persistent'

  echo '#net.ipv4.ip_forward=1 # ClusterCTRL' >> /etc/sysctl.conf
  cat << EOF >> /etc/iptables/rules.v4
# Generated by iptables-save v1.6.0 on Fri Mar 13 00:00:00 2018
*filter
:INPUT ACCEPT [7:1365]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A FORWARD -i br0 ! -o br0 -j ACCEPT
-A FORWARD -o br0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Fri Mar 13 00:00:00 2018
# Generated by iptables-save v1.6.0 on Fri Mar 13 00:00:00 2018
*nat
:PREROUTING ACCEPT [8:1421]
:INPUT ACCEPT [7:1226]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 172.19.181.0/24 ! -o br0 -j MASQUERADE
COMMIT
# Completed on Fri Mar 13 00:00:00 2018
EOF



  # Disable APIPA addresses on ethpiX and set fallback IPs

  # We give this an "unconfigured" IP of 172.19.181.253
  # Pi Zeros should be reconfigured to 172.19.181.X where X is the P number
  # NAT Controller is on 172.19.181.254
  # A USB network (usb0) device plugged into the controller will have fallback IP of 172.19.181.253

  cat << EOF >> /etc/dhcpcd.conf
# ClusterCTRL
reboot 15
denyinterfaces ethpi* ethupi* ethupi*.10 brint eth0 usb0.10

profile clusterctrl_fallback_usb0
static ip_address=172.19.181.253/24 #ClusterCTRL
static routers=172.19.181.254
static domain_name_servers=8.8.8.8 208.67.222.222

profile clusterctrl_fallback_br0
static ip_address=172.19.181.254/24

interface usb0
fallback clusterctrl_fallback_usb0

interface br0
fallback clusterctrl_fallback_br0
EOF

  # Enable uart with login
  /bin/bash -c "raspi-config nonint do_serial 0"

  # Enable I2C (used for I/O expander on Cluster HAT v2.x)
  /bin/bash -c "raspi-config nonint do_i2c 0"

  echo -e "mountd: 172.19.180.\nrpcbind: 172.19.180.\n" >> /etc/hosts.allow
  echo -e "mountd: ALL\nrpcbind: ALL\n" >> /etc/hosts.deny

  # Enable console on UART
  if [ "$SERIALAUTOLOGIN" = "1" ];then
   mkdir -p $MNT/etc/systemd/system/serial-getty@ttyS0.service.d/
   cat > $MNT/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I \$TERM
EOF
  fi

  # Extract files
  # TODO: change, git repo not checked out
  (tar --exclude=.git -cC files/ -f - .) | (tar -xC /)

  # Setup directories for rpiboot
  mkdir -p $MNT/var/lib/clusterctrl/boot
  mkdir -p $MNT/var/lib/clusterctrl/nfs
  if [ -z $BOOTCODE ];then
   ln -fs /boot/bootcode.bin $MNT/var/lib/clusterctrl/boot/
  elif [ ! $BOOTCODE = "none" ];then
   wget -O $MNT/var/lib/clusterctrl/boot/bootcode.bin $BOOTCODE
  fi

  # Enable clusterctrl init
  systemctl enable clusterctrl-init

  # Enable rpiboot for booting without SD cards
  systemctl enable clusterctrl-rpiboot
  # Disable nfs server (rely on clusterctrl-rpiboot to start it if needed)
  # TODO: try to understand
  systemctl disable nfs-kernel-server

  # Setup NFS exports for NFSROOT
  for ((P=1;P<=252;P++));do
   echo "/var/lib/clusterctrl/nfs/p$P 172.19.180.$P(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
   mkdir -p "/var/lib/clusterctrl/nfs/p$P"
  done

  # Setup config.txt file
  C=`grep -c "dtoverlay=dwc2,dr_mode=peripheral" /boot/config.txt`
  if [ $C -eq 0  ];then
   echo -e "# Load overlay to allow USB Gadget devices\n#dtoverlay=dwc2,dr_mode=peripheral" >> /boot/config.txt
  fi

  if [ $RELEASE = "RASPIOS64BULLSEYE" ] && [ ! -f "/boot/bcm2710-rpi-zero-2.dtb" ];then
   cp /boot/bcm2710-rpi-3-b.dtb /boot/bcm2710-rpi-zero-2.dtb
  fi

  rm -f /etc/ssh/*key*
  apt -y autoremove --purge
  apt clean

